version: "3.8"

services:
  service-mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: no
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - net-app-distri
  service-sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql
    restart: no
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=adminAppDist2024#
    networks:
    - net-app-distri
  service-postgres:
    image: postgres:alpine3.14
    container_name: database-postgres
    restart: no
    environment:
    - POSTGRES_PASSWORD=admin
    ports:
    - 5434:5432
    networks:
    - net-app-distri
  service-mongo:
    image: mongo:5.0.2
    container_name: database-mongo
    restart: no
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
    - 27018:27017
    networks:
    - net-app-distri
  service-mariadb:
    image: mariadb:10.2.36
    container_name: database-maria
    restart: no
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    ports:
    - 3310:3306
    - 33070:33060
    networks:
    - net-app-distri

networks:
  net-app-distri:
    name: netappdistri